# Worflow to publish to Surge
name: Surge

# Controls when the action will run.
on:
  pull_request:
    types: [synchronize]
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository
        uses: actions/checkout@v2
      - name: Build project
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build
        with:
          contentful_space_id: ${{ secrets.CONTENTFUL_SPACE_ID }}
          contentful_access_token: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: gatsby-build
          path: ./public/
  deploy:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: gatsby-build
          path: ./public/
      - name: Publish to surge.sh
        # You may pin to the exact commit or the version.
        # uses: dswistowski/surge-sh-action@341bcbd76a97da5e6b55ad92f53c0bf840e04c80
        uses: dswistowski/surge-sh-action@v1.0.0
        with:
          # your surge.sh domain to deploy
          domain: ${{ secrets.SURGE_DOMAIN }}
          # surge.sh login
          login: ${{ secrets.SURGE_LOGIN }}
          # surge.sh token, generate it with `surge token` command
          token: ${{ secrets.SURGE_TOKEN }}
          # your project path
          project: './public/' # optional, default is .
